name: mpxv-qc
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3
  - pysam=0.19.1
  - r-base=4
  - nextclade=3.4.0
  - snpEff=5.1
  - augur=24.3.0
  - newick_utils=1.6
  - bioconductor-ggtree=3.2.0
  - bedtools=2.30.0
  - samtools=1.17

