name: mpxv-qc
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3
  - r-base=4
  - nextclade=2.4.0
  - snpEff=5.1
  - augur=16.0.3
  - newick_utils=1.6
  - bioconductor-ggtree=3.2.0
